#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectionHubData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="COLHUBCOPY")]
	public partial class DataContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataContextDataContext() : 
				base(global::CollectionHubData.Properties.Settings.Default.COLHUBCOPYConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FULLNAME_FULLADDRESS_SEARCH")]
		public int FULLNAME_FULLADDRESS_SEARCH([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FIRSTNAME", DbType="NVarChar(50)")] string fIRSTNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MIDNAME", DbType="NVarChar(50)")] string mIDNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LASTNAME", DbType="NVarChar(50)")] string lASTNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ORGNAME", DbType="NVarChar(100)")] string oRGNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOB", DbType="NVarChar(20)")] string dOB, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NINO", DbType="NVarChar(20)")] string nINO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADDRNUMBER", DbType="NVarChar(50)")] string aDDRNUMBER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADDRNAME", DbType="NVarChar(100)")] string aDDRNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ADDRPOSTCODE", DbType="NVarChar(12)")] string aDDRPOSTCODE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fIRSTNAME, mIDNAME, lASTNAME, oRGNAME, dOB, nINO, aDDRNUMBER, aDDRNAME, aDDRPOSTCODE);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CHP_GetNameAddress")]
		public ISingleResult<CHP_GetNameAddressResult> CHP_GetNameAddress([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SOURCE", DbType="NVarChar(5)")] string sOURCE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SOURCE_REF", DbType="Int")] System.Nullable<int> sOURCE_REF)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sOURCE, sOURCE_REF);
			return ((ISingleResult<CHP_GetNameAddressResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CHP_GETPERSONDEBTS")]
		public ISingleResult<CHP_GETPERSONDEBTSResult> CHP_GETPERSONDEBTS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Source", DbType="NVarChar(5)")] string source, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Source_ref", DbType="Int")] System.Nullable<int> source_ref)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), source, source_ref);
			return ((ISingleResult<CHP_GETPERSONDEBTSResult>)(result.ReturnValue));
		}
	}
	
	public partial class CHP_GetNameAddressResult
	{
		
		private string _SOURCE;
		
		private string _PIN;
		
		private System.Nullable<int> _UPRN;
		
		private string _Fullname;
		
		private string _FullAddress;
		
		private System.Nullable<decimal> _DebtOS;
		
		private System.Nullable<decimal> _TotalDebt;
		
		private string _RespOfficer;
		
		public CHP_GetNameAddressResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOURCE", DbType="NChar(10)")]
		public string SOURCE
		{
			get
			{
				return this._SOURCE;
			}
			set
			{
				if ((this._SOURCE != value))
				{
					this._SOURCE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIN", DbType="NVarChar(25)")]
		public string PIN
		{
			get
			{
				return this._PIN;
			}
			set
			{
				if ((this._PIN != value))
				{
					this._PIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPRN", DbType="Int")]
		public System.Nullable<int> UPRN
		{
			get
			{
				return this._UPRN;
			}
			set
			{
				if ((this._UPRN != value))
				{
					this._UPRN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="NVarChar(400)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this._Fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullAddress", DbType="NVarChar(420)")]
		public string FullAddress
		{
			get
			{
				return this._FullAddress;
			}
			set
			{
				if ((this._FullAddress != value))
				{
					this._FullAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DebtOS", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> DebtOS
		{
			get
			{
				return this._DebtOS;
			}
			set
			{
				if ((this._DebtOS != value))
				{
					this._DebtOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalDebt", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> TotalDebt
		{
			get
			{
				return this._TotalDebt;
			}
			set
			{
				if ((this._TotalDebt != value))
				{
					this._TotalDebt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RespOfficer", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string RespOfficer
		{
			get
			{
				return this._RespOfficer;
			}
			set
			{
				if ((this._RespOfficer != value))
				{
					this._RespOfficer = value;
				}
			}
		}
	}
	
	public partial class CHP_GETPERSONDEBTSResult
	{
		
		private int _cd_id;
		
		private string _cd_source;
		
		private string _cd_source_accref;
		
		private string _cd_debt_ref;
		
		private System.Nullable<decimal> _cd_debt_total;
		
		private System.Nullable<decimal> _cd_os_bal;
		
		private System.Nullable<decimal> _cd_party_pin;
		
		private string _cd_prop_ref;
		
		private System.Nullable<System.DateTime> _cd_debt_date;
		
		private string _Recovery_Cycle;
		
		private System.Nullable<int> _Last_Action_Date;
		
		private string _cd_Status;
		
		private string _cd_type;
		
		public CHP_GETPERSONDEBTSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_id", DbType="Int NOT NULL")]
		public int cd_id
		{
			get
			{
				return this._cd_id;
			}
			set
			{
				if ((this._cd_id != value))
				{
					this._cd_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_source", DbType="NChar(10)")]
		public string cd_source
		{
			get
			{
				return this._cd_source;
			}
			set
			{
				if ((this._cd_source != value))
				{
					this._cd_source = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_source_accref", DbType="VarChar(20)")]
		public string cd_source_accref
		{
			get
			{
				return this._cd_source_accref;
			}
			set
			{
				if ((this._cd_source_accref != value))
				{
					this._cd_source_accref = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_debt_ref", DbType="VarChar(20)")]
		public string cd_debt_ref
		{
			get
			{
				return this._cd_debt_ref;
			}
			set
			{
				if ((this._cd_debt_ref != value))
				{
					this._cd_debt_ref = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_debt_total", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> cd_debt_total
		{
			get
			{
				return this._cd_debt_total;
			}
			set
			{
				if ((this._cd_debt_total != value))
				{
					this._cd_debt_total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_os_bal", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> cd_os_bal
		{
			get
			{
				return this._cd_os_bal;
			}
			set
			{
				if ((this._cd_os_bal != value))
				{
					this._cd_os_bal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_party_pin", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> cd_party_pin
		{
			get
			{
				return this._cd_party_pin;
			}
			set
			{
				if ((this._cd_party_pin != value))
				{
					this._cd_party_pin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_prop_ref", DbType="VarChar(50)")]
		public string cd_prop_ref
		{
			get
			{
				return this._cd_prop_ref;
			}
			set
			{
				if ((this._cd_prop_ref != value))
				{
					this._cd_prop_ref = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_debt_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> cd_debt_date
		{
			get
			{
				return this._cd_debt_date;
			}
			set
			{
				if ((this._cd_debt_date != value))
				{
					this._cd_debt_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recovery_Cycle", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Recovery_Cycle
		{
			get
			{
				return this._Recovery_Cycle;
			}
			set
			{
				if ((this._Recovery_Cycle != value))
				{
					this._Recovery_Cycle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Action_Date", DbType="Int")]
		public System.Nullable<int> Last_Action_Date
		{
			get
			{
				return this._Last_Action_Date;
			}
			set
			{
				if ((this._Last_Action_Date != value))
				{
					this._Last_Action_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_Status", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string cd_Status
		{
			get
			{
				return this._cd_Status;
			}
			set
			{
				if ((this._cd_Status != value))
				{
					this._cd_Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cd_type", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string cd_type
		{
			get
			{
				return this._cd_type;
			}
			set
			{
				if ((this._cd_type != value))
				{
					this._cd_type = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
